import os
import requests

# List of URLs for downloading code files
urls = [
    "https://raw.githubusercontent.com/actix/actix-web/master/actix-web/src/app_service.rs",
    "https://raw.githubusercontent.com/alacritty/alacritty/master/alacritty_terminal/src/lib.rs",
    "https://raw.githubusercontent.com/babel/babel/main/packages/babel-standalone/babel.js",
    "https://raw.githubusercontent.com/babel/babel/main/packages/babel-standalone/src/index.js", 
    "https://raw.githubusercontent.com/bevyengine/bevy/master/crates/bevy_app/src/app.rs",
    "https://raw.githubusercontent.com/blueimp/jQuery-File-Upload/master/js/jquery.fileupload.js",
    "https://raw.githubusercontent.com/boostorg/beast/master/test/beast/core/detail/base64.cpp",
    "https://raw.githubusercontent.com/catchorg/Catch2/master/tests/Catch2Tests.cpp",
    "https://raw.githubusercontent.com/catchorg/Catch2/master/tests/SelfTest/UsageTests/ConditionTests.cpp",
    "https://raw.githubusercontent.com/chromium/chromium/main/content/browser/renderer_host/render_widget_host_impl.cc",
    "https://raw.githubusercontent.com/cpp-netlib/cpp-netlib/master/cppnetlib-utils/src/util/string_util.cpp",
    "https://raw.githubusercontent.com/cppnetlib/cppnetlib/master/cppnetlib-utils/src/util/string_util.cpp",
    "https://raw.githubusercontent.com/d3/d3/main/index.js",
    "https://raw.githubusercontent.com/d3/d3/main/src/index.js",
    "https://raw.githubusercontent.com/diesel-rs/diesel/master/diesel/src/lib.rs",
    "https://raw.githubusercontent.com/django/django/main/django/db/models/query.py",
    "https://raw.githubusercontent.com/eigen/eigen/master/test/main.cpp",
    "https://raw.githubusercontent.com/eigen/eigen/master/test/product_small.cpp",
    "https://raw.githubusercontent.com/expressjs/express/master/lib/application.js",
    "https://raw.githubusercontent.com/facebook/react/main/packages/react/src/React.js",
    "https://raw.githubusercontent.com/facebook/react/main/src/React.js",
    "https://raw.githubusercontent.com/firecracker-microvm/firecracker/master/src/vmm/src/lib.rs",
    "https://raw.githubusercontent.com/fullcalendar/fullcalendar/main/packages/core/src/core.js",
    "https://raw.githubusercontent.com/fullcalendar/fullcalendar/main/packages/core/src/index.ts",
    "https://raw.githubusercontent.com/GNOME/gtk/master/gtk/gtkwindow.c",
    "https://raw.githubusercontent.com/google/googletest/master/googletest/src/gtest-all.cc",
    "https://raw.githubusercontent.com/huggingface/transformers/main/src/transformers/models/bert/modeling_bert.py",
    "https://raw.githubusercontent.com/jquery/jquery/main/src/core.js",
    "https://raw.githubusercontent.com/jupyter/notebook/master/notebook/services/contents/filemanager.py",
    "https://raw.githubusercontent.com/jupyter/notebook/master/notebook/services/contents/filemanager.py",
    "https://raw.githubusercontent.com/libevent/libevent/master/event.c",
    "https://raw.githubusercontent.com/libuv/libuv/v1.x/src/unix/stream.c",
    "https://raw.githubusercontent.com/llvm/llvm-project/main/llvm/lib/ExecutionEngine/Interpreter/Execution.cpp",
    "https://raw.githubusercontent.com/lodash/lodash/main/lodash.js",
    "https://raw.githubusercontent.com/madler/zlib/master/deflate.c",
    "https://raw.githubusercontent.com/MariaDB/server/10.6/sql/mariadb.sql",
    "https://raw.githubusercontent.com/MariaDB/server/10.6/sql/sql_yacc.yy",
    "https://raw.githubusercontent.com/matplotlib/matplotlib/main/lib/matplotlib/pyplot.py",
    "https://raw.githubusercontent.com/moment/moment/master/moment.js",
    "https://raw.githubusercontent.com/mrdoob/three.js/dev/build/three.module.js",
    "https://raw.githubusercontent.com/mysql/mysql-server/8.0/mysql-test/suite/innodb/t/innodb.test",
    "https://raw.githubusercontent.com/mysql/mysql-server/8.0/mysql-test/t/sakila-schema.sql",
    "https://raw.githubusercontent.com/mysql/mysql-server/8.0/sql/sql_base.cc",
    "https://raw.githubusercontent.com/mysql/mysql-server/8.0/storage/innobase/row/row0mysql.c",
    "https://raw.githubusercontent.com/mysql/mysql-server/8.0/storage/myisam/mi_delete.c",
    "https://raw.githubusercontent.com/nlohmann/json/master/test/src/unit-json.cpp",
    "https://raw.githubusercontent.com/nlohmann/json/master/test/src/unit.cpp",
    "https://raw.githubusercontent.com/nodejs/node/main/lib/internal/bootstrap/node.js",
    "https://raw.githubusercontent.com/numpy/numpy/main/numpy/core/multiarray.py",
    "https://raw.githubusercontent.com/opencv/opencv/4.x/modules/calib3d/src/calibinit.cpp",
    "https://raw.githubusercontent.com/openssl/openssl/master/crypto/evp/evp_enc.c",
    "https://raw.githubusercontent.com/pallets/flask/main/src/flask/app.py",
    "https://raw.githubusercontent.com/pandas-dev/pandas/main/pandas/core/frame.py",
    "https://raw.githubusercontent.com/paritytech/substrate/master/client/rpc/src/lib.rs",
    "https://raw.githubusercontent.com/pgRouting/pgrouting/master/doc/pgRouting-workshop-2015-03-25.sql",
    "https://raw.githubusercontent.com/pgRouting/pgrouting/master/doc/queries/basic.sql",
    "https://raw.githubusercontent.com/postgres/postgres/master/contrib/postgis/postgis.sql",
    "https://raw.githubusercontent.com/postgres/postgres/master/src/backend/utils/adt/geo_ops.c",
    "https://raw.githubusercontent.com/psf/requests/main/requests/api.py",
    "https://raw.githubusercontent.com/psf/requests/main/requests/sessions.py",
    "https://raw.githubusercontent.com/pytorch/pytorch/main/aten/src/ATen/native/LinearAlgebra.cpp",
    "https://raw.githubusercontent.com/pytorch/pytorch/main/torch/nn/modules/module.py",
    "https://raw.githubusercontent.com/PyTorchLightning/pytorch-lightning/master/pytorch_lightning/trainer/trainer.py",
    "https://raw.githubusercontent.com/qt/qtbase/5.15/src/widgets/kernel/qapplication.cpp",
    "https://raw.githubusercontent.com/rust-lang/rust/main/compiler/rustc_interface/src/lib.rs",
    "https://raw.githubusercontent.com/rust-lang/rust/main/library/core/src/lib.rs",
    "https://raw.githubusercontent.com/rust-lang/rust/master/compiler/rustc_interface/src/lib.rs",
    "https://raw.githubusercontent.com/rust-lang/rust/master/library/core/src/lib.rs",
    "https://raw.githubusercontent.com/rustls/rustls/master/rustls/src/lib.rs",
    "https://raw.githubusercontent.com/rusty-fork/sctp-rs/master/src/lib.rs",
    "https://raw.githubusercontent.com/rusty-fork/sctp-rs/master/src/socket.rs",
    "https://raw.githubusercontent.com/scikit-learn/scikit-learn/main/sklearn/linear_model/_logistic.py",
    "https://raw.githubusercontent.com/scipy/scipy/main/scipy/stats/stats.py",
    "https://raw.githubusercontent.com/serde-rs/serde/master/serde/src/lib.rs",
    "https://raw.githubusercontent.com/servo/servo/main/components/script/dom/bindings/codegen/Promise.rs",
    "https://raw.githubusercontent.com/servo/servo/master/components/script/dom/promise.rs",
    "https://raw.githubusercontent.com/socketio/socket.io/main/dist/socket.io.js",
    "https://raw.githubusercontent.com/sqlite/sqlite/master/ext/rtree/rtree.c",
    "https://raw.githubusercontent.com/sqlite/sqlite/master/ext/rtree/rtree.sql",
    "https://raw.githubusercontent.com/sqlite/sqlite/master/src/main.c",
    "https://raw.githubusercontent.com/sqlite/sqlite/master/src/sqlite3.c",
    "https://raw.githubusercontent.com/sympy/sympy/master/sympy/core/expr.py",
    "https://raw.githubusercontent.com/tensorflow/tensorflow/main/tensorflow/core/common_runtime/gpu/gpu_device.cc",
    "https://raw.githubusercontent.com/tensorflow/tensorflow/main/tensorflow/core/common_runtime/gpu/gpu_event_mgr.cc",
    "https://raw.githubusercontent.com/tensorflow/tensorflow/main/tensorflow/python/training/training.py",
    "https://raw.githubusercontent.com/tensorflow/tensorflow/main/tensorflow/python/training/training_ops.py",
    "https://raw.githubusercontent.com/the-tcpdump-group/libpcap/master/pcap.c",
    "https://raw.githubusercontent.com/timescale/timescaledb/master/sql/timescaledb.sql",
    "https://raw.githubusercontent.com/tokio-rs/tokio/main/tokio/src/runtime.rs",
    "https://raw.githubusercontent.com/tokio-rs/tokio/master/tokio/src/runtime/runtime.rs",
    "https://raw.githubusercontent.com/torvalds/linux/master/arch/x86/entry/entry_64.S",
    "https://raw.githubusercontent.com/torvalds/linux/master/arch/x86/entry/vsyscall/vsyscall_64.c",
    "https://raw.githubusercontent.com/torvalds/linux/master/arch/x86/kernel/entry_64.S",
    "https://raw.githubusercontent.com/torvalds/linux/master/arch/x86/kernel/head_64.S",
    "https://raw.githubusercontent.com/torvalds/linux/master/arch/x86/kernel/process_64.c",
    "https://raw.githubusercontent.com/torvalds/linux/master/arch/x86/kernel/process_64.S",
    "https://raw.githubusercontent.com/torvalds/linux/master/arch/x86/kernel/vmlinux.lds.S",
    "https://raw.githubusercontent.com/torvalds/linux/master/arch/x86/kernel/vsyscall/vsyscall_64.S",
    "https://raw.githubusercontent.com/torvalds/linux/master/arch/x86/lib/atomic.S",
    "https://raw.githubusercontent.com/torvalds/linux/master/arch/x86/lib/atomic64_32.S",
    "https://raw.githubusercontent.com/torvalds/linux/master/arch/x86/mm/fault.c",
    "https://raw.githubusercontent.com/torvalds/linux/master/arch/x86/mm/fault.S",
    "https://raw.githubusercontent.com/torvalds/linux/master/drivers/net/ethernet/intel/e1000/e1000_main.c",
    "https://raw.githubusercontent.com/torvalds/linux/master/fs/ext4/inode.c",
    "https://raw.githubusercontent.com/torvalds/linux/master/init/main.c",
    "https://raw.githubusercontent.com/torvalds/linux/master/kernel/sched/core.c",
    "https://raw.githubusercontent.com/torvalds/linux/master/mm/vmscan.c",
    "https://raw.githubusercontent.com/vuejs/vue/main/src/platforms/web/runtime/index.js",
    "https://raw.githubusercontent.com/webpack/webpack/master/lib/webpack.js",
]

# Create the "code_samples" folder if it doesn't exist
folder = "code_samples"
if not os.path.exists(folder):
    os.makedirs(folder)

# Download each file and save as 1.txt, 2.txt, etc.
i = 1
for url in urls:
    save_path = os.path.join(folder, f"{i}.txt")
    response = requests.get(url)
    if response.status_code == 200:
        with open(save_path, 'w', encoding='utf-8') as f:
            f.write(response.text)
        print(f"Downloaded {url} as {save_path}")
        i += 1
    else:
        print(f"Failed to download {url}")
